# Avoid accidentally quitting - use ^C instead
confirmOnQuit: true
git:
  commit:
    signOff: false
  overrideGpg: true
  pagers:
    # cycle through pagers with `|`
    - colorArg: always
      # WARN: Workaround for non-working dark/light detection
      # - when using delta inside lazygit
      # - see https://github.com/jesseduffield/lazygit/issues/4550
      pager: ~/.config/lazygit/delta.sh --paging=never --true-color=never
    - colorArg: always
      externalDiffCommand: diffyml
services:
  git.netic.dk: bitbucketServer:git.netic.dk
