git:
  commit:
    signOff: false
  pull:
    mode: 'auto'
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never --true-color=never
services:
  'git.rtx.mapspeople.com': 'gitlab:git.rtx.mapspeople.com'
